"""
mwrap_fmexgen.py — Fortran MEX gateway code generator (free-form F90).

Generates free-form Fortran 90 (.f90) MEX gateway files using
iso_c_binding and bind(C) for direct C interop with the MEX API.
No C bridge file, no name mangling, no preprocessor.

Copyright (c) 2007-2008  David Bindel
See the file COPYING for copying permissions

Fortran MEX backend by Zydrunas Gimbutas (2026),
with assistance from Claude Code / Claude Opus 4.6 (Anthropic).
"""

import sys
from mwrap_ast import (
    VT, Expr, TypeQual, Var, Func,
    id_string, print_func,
    is_array, is_obj, complex_tinfo, nullable_return,
    iospec_is_input, iospec_is_output,
)


# ===================================================================
# Type mapping: mwrap base types -> Fortran iso_c_binding types
# ===================================================================

# Maps mwrap base type to (fortran_type, is_complex, is_native_double)
# is_native_double: True if mxArray data is double and can be used directly
FMEX_TYPE_MAP = {
    "double":   ("real(c_double)",             False, True),
    "float":    ("real(c_float)",              False, False),
    "int":      ("integer(c_int)",             False, False),
    "int32_t":  ("integer(c_int32_t)",         False, False),
    "int64_t":  ("integer(c_int64_t)",         False, False),
    "dcomplex": ("complex(c_double_complex)",  True,  True),
    "fcomplex": ("complex(c_float_complex)",   True,  False),
}

# With -i8, integer types are promoted
FMEX_TYPE_MAP_I8 = {
    "double":   ("real(c_double)",             False, True),
    "float":    ("real(c_float)",              False, False),
    "int":      ("integer(8)",                 False, False),
    "int32_t":  ("integer(8)",                 False, False),
    "int64_t":  ("integer(8)",                 False, False),
    "dcomplex": ("complex(c_double_complex)",  True,  True),
    "fcomplex": ("complex(c_float_complex)",   True,  False),
}

_DEFAULT_TYPE = ("real(c_double)", False, True)


def _fort_type(basetype, i8_mode):
    """Get (fortran_type, is_complex, is_native) for a base type."""
    m = FMEX_TYPE_MAP_I8 if i8_mode else FMEX_TYPE_MAP
    return m.get(basetype, _DEFAULT_TYPE)


def _int_kind(i8_mode):
    """Fortran integer kind for user-facing integers."""
    return "8" if i8_mode else "c_int"


# ===================================================================
# Variable naming
# ===================================================================

def vname(v):
    if v.iospec == 'o':
        return f"out{v.output_label}_"
    return f"in{v.input_label}_"


# ===================================================================
# Classify variables for code generation
# ===================================================================

def _is_scalar_array(v):
    """True if v is an array with all-literal dimensions (e.g. int[1])."""
    if not (v.qual and v.qual.args):
        return False
    return all(e.value.isdigit() for e in v.qual.args)


def _dim_product(v):
    """Product of literal dimension values, or None if not all-literal."""
    if not (v.qual and v.qual.args):
        return None
    try:
        p = 1
        for e in v.qual.args:
            p *= int(e.value)
        return p
    except ValueError:
        return None


def _needs_conversion(basetype):
    """True if mxArray data (double) must be converted for this type."""
    return basetype not in ("double", "dcomplex")


# ===================================================================
# Helper: dimension expression in Fortran
# ===================================================================

def _alloc_size_expr(args):
    """Fortran expression for product of dim args."""
    if not args:
        return "1"
    return " * ".join(f"dim{e.input_label}_" for e in args)


def _dim_label(e):
    return f"dim{e.input_label}_"


# ===================================================================
# Write helpers (free-form, no column limit concern)
# ===================================================================

def _w(fp, text, indent=2):
    """Write an indented line."""
    fp.write(" " * indent + text + "\n")


def _wc(fp, text, indent=2):
    """Write a comment line."""
    fp.write(" " * indent + "! " + text + "\n")


# ===================================================================
# Print the module (emitted once at top of file)
# ===================================================================

MWRAP_FMEX_BANNER = """\
! ---------------------------------------------------------------------
! Automatically generated by MWrap (Fortran MEX backend)
! MWrap version 1.4
!
! Copyright (c) 2007-2008 David Bindel
! MIT License -- see COPYING for details.
! You may distribute mwrap-generated source under any license.
! ---------------------------------------------------------------------
"""


def print_fmex_init(fp, ctx, support_text):
    """Write banner + mwrap_mex module (from support file)."""
    fp.write(MWRAP_FMEX_BANNER)
    fp.write("\n")
    fp.write(support_text)
    fp.write("\n")


# ===================================================================
# Per-stub: declare local variables
# ===================================================================

def _print_declarations(fp, f, i8_mode):
    """Declare all local variables for a stub."""
    fort_int = f"integer({_int_kind(i8_mode)})"

    # Dimension variables
    for v in (f.ret or []) + f.args:
        if v.qual and v.qual.args:
            for e in v.qual.args:
                _w(fp, f"integer(c_size_t) :: {_dim_label(e)}", 4)

    # Input variables
    for v in f.args:
        if v.iospec == 'o' or v.tinfo == VT.const:
            continue

        il = v.input_label
        ft, is_cplx, is_native = _fort_type(v.basetype, i8_mode)

        if is_array(v.tinfo):
            if _is_scalar_array(v) and _dim_product(v) == 1:
                # Scalar-by-reference: local variable, passed by ref
                _w(fp, f"{ft} :: in{il}_", 4)
            elif is_native:
                # Native type: use c_f_pointer directly
                _w(fp, f"{ft}, pointer :: in{il}_(:)", 4)
            else:
                # Needs conversion from double
                _w(fp, f"{ft}, allocatable :: in{il}_(:)", 4)
                _w(fp, f"real(c_double), pointer :: in{il}_dbl_(:)", 4)
        elif v.tinfo in (VT.p_scalar, VT.p_cscalar, VT.p_zscalar):
            _w(fp, f"{ft} :: in{il}_", 4)
        elif v.tinfo == VT.string:
            _w(fp, f"character(len=1024) :: in{il}_", 4)
            _w(fp, f"integer(c_int) :: in{il}_stat_", 4)

    # Output variables
    for v in (f.ret or []) + f.args:
        if v.iospec != 'o':
            continue
        ol = v.output_label
        ft, is_cplx, is_native = _fort_type(v.basetype, i8_mode)

        if is_array(v.tinfo):
            if is_native:
                _w(fp, f"{ft}, pointer :: out{ol}_(:)", 4)
            else:
                _w(fp, f"{ft}, allocatable :: out{ol}_(:)", 4)
                _w(fp, f"real(c_double), pointer :: out{ol}_dbl_(:)", 4)
        elif v.tinfo in (VT.scalar, VT.p_scalar):
            _w(fp, f"{ft} :: out{ol}_", 4)
            _w(fp, f"real(c_double), pointer :: out{ol}_dbl_(:)", 4)
        elif v.tinfo in (VT.p_cscalar, VT.p_zscalar):
            _w(fp, f"{ft} :: out{ol}_", 4)

    # Inout arrays: need pointers for input copy and marshal temps
    for v in f.args:
        if v.iospec != 'b':
            continue
        il = v.input_label
        ol = v.output_label
        ft, is_cplx, is_native = _fort_type(v.basetype, i8_mode)

        if is_array(v.tinfo):
            if _is_scalar_array(v) and _dim_product(v) == 1:
                # Scalar inout: need a double pointer for marshalling output
                _w(fp, f"real(c_double), pointer :: out{ol}_dbl_(:)", 4)
            elif is_native:
                # Need a pointer for output + pointer for input copy
                _w(fp, f"{ft}, pointer :: inout{il}_src_(:)", 4)
            else:
                _w(fp, f"real(c_double), pointer :: inout{il}_src_dbl_(:)", 4)
            # Dimension vars for inout arrays without explicit dims
            if not (v.qual and v.qual.args):
                _w(fp, f"integer(c_size_t) :: inout{il}_m_, inout{il}_n_", 4)

    # Return value
    if f.ret:
        v = f.ret[0]
        if v.tinfo == VT.scalar:
            ft, _, _ = _fort_type(v.basetype, i8_mode)
            _w(fp, f"{ft} :: out0_", 4)
            _w(fp, f"real(c_double), pointer :: ret_dbl_(:)", 4)

    # Temp integer for loop index (if needed for conversion)
    needs_loop = False
    for v in (f.ret or []) + f.args:
        if is_array(v.tinfo) and _needs_conversion(v.basetype):
            if not (_is_scalar_array(v) and _dim_product(v) == 1):
                needs_loop = True
    if needs_loop:
        _w(fp, f"integer(c_size_t) :: mwf_i_", 4)

    fp.write("\n")


# ===================================================================
# Per-stub: unpack dimensions
# ===================================================================

def _print_unpack_dims(fp, f, i8_mode):
    has_dims = False
    for v in (f.ret or []) + f.args:
        if v.qual and v.qual.args:
            has_dims = True
            break
    if not has_dims:
        return

    _wc(fp, "unpack dimensions", 4)
    for v in (f.ret or []) + f.args:
        if v.qual and v.qual.args:
            for e in v.qual.args:
                idx = e.input_label + 1
                _w(fp, f"{_dim_label(e)} = int(mxGetScalar(prhs({idx})), c_size_t)", 4)
    fp.write("\n")


# ===================================================================
# Per-stub: unpack inputs
# ===================================================================

def _print_unpack_inputs(fp, f, i8_mode):
    has_inputs = any(v.iospec != 'o' and v.tinfo != VT.const for v in f.args)
    if not has_inputs:
        return

    _wc(fp, "unpack inputs", 4)
    fort_int = f"integer({_int_kind(i8_mode)})"

    for v in f.args:
        if v.iospec == 'o' or v.tinfo == VT.const:
            continue

        il = v.input_label
        idx = il + 1
        ft, is_cplx, is_native = _fort_type(v.basetype, i8_mode)

        if is_array(v.tinfo):
            da = v.qual.args if v.qual else []

            if _is_scalar_array(v) and _dim_product(v) == 1:
                # Scalar-by-reference: extract via mxGetScalar
                bt = v.basetype
                if bt in ("int", "int32_t"):
                    kind = _int_kind(i8_mode)
                    _w(fp, f"in{il}_ = int(mxGetScalar(prhs({idx})), {kind})", 4)
                elif bt == "int64_t":
                    _w(fp, f"in{il}_ = int(mxGetScalar(prhs({idx})), c_int64_t)", 4)
                else:
                    _w(fp, f"in{il}_ = mxGetScalar(prhs({idx}))", 4)
            elif is_native:
                # Native type: use c_f_pointer
                if da:
                    sz = _alloc_size_expr(da)
                else:
                    sz = f"int(mxGetM(prhs({idx})) * mxGetN(prhs({idx})), c_size_t)"
                _w(fp, f"call c_f_pointer(mxGetPr(prhs({idx})), in{il}_, [{sz}])", 4)
            else:
                # Needs conversion from double
                if da:
                    sz = _alloc_size_expr(da)
                else:
                    sz = f"int(mxGetM(prhs({idx})) * mxGetN(prhs({idx})), c_size_t)"
                _w(fp, f"call c_f_pointer(mxGetPr(prhs({idx})), in{il}_dbl_, [{sz}])", 4)
                _w(fp, f"allocate(in{il}_({sz}))", 4)
                _w(fp, f"do mwf_i_ = 1, {sz}", 4)
                _w(fp, f"  in{il}_(mwf_i_) = int(in{il}_dbl_(mwf_i_), {_int_kind(i8_mode)})", 6)
                _w(fp, f"end do", 4)

        elif v.tinfo in (VT.p_scalar, VT.p_cscalar, VT.p_zscalar):
            bt = v.basetype
            if bt in ("int", "int32_t"):
                kind = _int_kind(i8_mode)
                _w(fp, f"in{il}_ = int(mxGetScalar(prhs({idx})), {kind})", 4)
            elif bt == "int64_t":
                _w(fp, f"in{il}_ = int(mxGetScalar(prhs({idx})), c_int64_t)", 4)
            elif bt in ("double", "float"):
                _w(fp, f"in{il}_ = mxGetScalar(prhs({idx}))", 4)
            else:
                _w(fp, f"in{il}_ = mxGetScalar(prhs({idx}))", 4)

        elif v.tinfo == VT.string:
            _w(fp, f"in{il}_stat_ = mxGetString(prhs({idx}), in{il}_, 1024_c_int)", 4)

    fp.write("\n")


# ===================================================================
# Per-stub: handle inout arrays
# ===================================================================

def _print_handle_inout(fp, f, i8_mode):
    """For inout arrays: create output mxArray, copy input data, set pointer."""
    has_inout = any(v.iospec == 'b' and is_array(v.tinfo) for v in f.args)
    if not has_inout:
        return

    _wc(fp, "handle inout arrays: create output, copy input", 4)

    for v in f.args:
        if v.iospec != 'b' or not is_array(v.tinfo):
            continue

        il = v.input_label
        ol = v.output_label
        idx_in = il + 1
        idx_out = ol + 1
        ft, is_cplx, is_native = _fort_type(v.basetype, i8_mode)
        da = v.qual.args if v.qual else []

        if _is_scalar_array(v) and _dim_product(v) == 1:
            # Scalar inout: already handled in unpack_inputs
            # Will marshal after the call
            continue

        # Get dimensions
        if da:
            if len(da) == 1:
                dim_m = _dim_label(da[0])
                dim_n = "1_c_size_t"
            elif len(da) == 2:
                dim_m = _dim_label(da[0])
                dim_n = _dim_label(da[1])
            else:
                dim_m = _alloc_size_expr(da)
                dim_n = "1_c_size_t"
            sz = _alloc_size_expr(da)
        else:
            # No explicit dims: use input array size
            _w(fp, f"inout{il}_m_ = mxGetM(prhs({idx_in}))", 4)
            _w(fp, f"inout{il}_n_ = mxGetN(prhs({idx_in}))", 4)
            dim_m = f"inout{il}_m_"
            dim_n = f"inout{il}_n_"
            sz = f"inout{il}_m_ * inout{il}_n_"

        # Create output mxArray
        cflag = "1" if is_cplx else "0"
        _w(fp, f"plhs({idx_out}) = mxCreateDoubleMatrix({dim_m}, {dim_n}, {cflag})", 4)

        if is_native:
            # Copy input data to output, point in{il}_ at output
            _w(fp, f"call c_f_pointer(mxGetPr(prhs({idx_in})), inout{il}_src_, [{sz}])", 4)
            _w(fp, f"call c_f_pointer(mxGetPr(plhs({idx_out})), in{il}_, [{sz}])", 4)
            _w(fp, f"in{il}_(1:{sz}) = inout{il}_src_(1:{sz})", 4)
        else:
            # Need to convert from double, write back after call
            _w(fp, f"call c_f_pointer(mxGetPr(prhs({idx_in})), inout{il}_src_dbl_, [{sz}])", 4)
            _w(fp, f"allocate(in{il}_({sz}))", 4)
            _w(fp, f"do mwf_i_ = 1, {sz}", 4)
            _w(fp, f"  in{il}_(mwf_i_) = int(inout{il}_src_dbl_(mwf_i_), {_int_kind(i8_mode)})", 6)
            _w(fp, f"end do", 4)

    fp.write("\n")


# ===================================================================
# Per-stub: allocate pure output arrays
# ===================================================================

def _print_alloc_outputs(fp, f, i8_mode):
    """Allocate output-only arrays."""
    has_out = False
    for v in (f.ret or []) + f.args:
        if v.iospec == 'o' and is_array(v.tinfo):
            has_out = True
    if not has_out:
        return

    _wc(fp, "allocate output arrays", 4)
    for v in (f.ret or []) + f.args:
        if v.iospec != 'o' or not is_array(v.tinfo):
            continue
        ol = v.output_label
        idx = ol + 1
        ft, is_cplx, is_native = _fort_type(v.basetype, i8_mode)
        da = v.qual.args if v.qual else []

        if len(da) == 1:
            dim_m = _dim_label(da[0])
            dim_n = "1_c_size_t"
        elif len(da) == 2:
            dim_m = _dim_label(da[0])
            dim_n = _dim_label(da[1])
        else:
            dim_m = _alloc_size_expr(da)
            dim_n = "1_c_size_t"
        sz = _alloc_size_expr(da)

        cflag = "1" if is_cplx else "0"
        _w(fp, f"plhs({idx}) = mxCreateDoubleMatrix({dim_m}, {dim_n}, {cflag})", 4)

        if is_native:
            _w(fp, f"call c_f_pointer(mxGetPr(plhs({idx})), out{ol}_, [{sz}])", 4)
        else:
            _w(fp, f"allocate(out{ol}_({sz}))", 4)

    fp.write("\n")


# ===================================================================
# Per-stub: make the call
# ===================================================================

def _print_make_call(fp, f, i8_mode):
    _wc(fp, "make the call", 4)

    # Build argument list
    call_args = []
    for v in f.args:
        if v.tinfo == VT.const:
            call_args.append(v.name)
        elif is_array(v.tinfo):
            n = vname(v)
            if _is_scalar_array(v) and _dim_product(v) == 1:
                # Scalar by ref: pass local variable (Fortran passes by ref)
                call_args.append(n)
            else:
                # Array: pass the pointer/allocatable
                call_args.append(n)
        elif v.tinfo in (VT.p_scalar, VT.p_cscalar, VT.p_zscalar):
            call_args.append(vname(v))
        elif v.tinfo == VT.string:
            call_args.append(vname(v))
        else:
            call_args.append(vname(v))

    args_str = ", &\n        ".join(call_args) if len(call_args) > 4 else ", ".join(call_args)

    if f.ret and f.ret[0].tinfo == VT.scalar:
        _w(fp, f"out0_ = {f.funcv}({args_str})", 4)
    else:
        _w(fp, f"call {f.funcv}({args_str})", 4)

    fp.write("\n")


# ===================================================================
# Per-stub: marshal results
# ===================================================================

def _print_marshal_results(fp, f, i8_mode):
    """Marshal scalar outputs and inout scalars back to plhs."""
    has_marshal = False

    # Return value
    if f.ret and f.ret[0].tinfo == VT.scalar:
        has_marshal = True
    # Inout scalar arrays (int[1])
    for v in f.args:
        if v.iospec == 'b' and is_array(v.tinfo) and _is_scalar_array(v) and _dim_product(v) == 1:
            has_marshal = True
    # Output scalar args
    for v in (f.ret or []) + f.args:
        if v.iospec == 'o' and v.tinfo in (VT.scalar, VT.p_scalar):
            has_marshal = True
    # Inout non-native arrays (need to convert back)
    for v in f.args:
        if v.iospec == 'b' and is_array(v.tinfo) and _needs_conversion(v.basetype):
            if not (_is_scalar_array(v) and _dim_product(v) == 1):
                has_marshal = True

    if not has_marshal:
        return

    _wc(fp, "marshal outputs", 4)

    # Return value (scalar)
    if f.ret:
        v = f.ret[0]
        if v.tinfo == VT.scalar:
            _w(fp, f"plhs(1) = mxCreateDoubleMatrix(1_c_size_t, 1_c_size_t, 0)", 4)
            _w(fp, f"call c_f_pointer(mxGetPr(plhs(1)), ret_dbl_, [1])", 4)
            _w(fp, f"ret_dbl_(1) = dble(out0_)", 4)

    # Inout scalar arrays (e.g. inout int[1] ier)
    for v in f.args:
        if v.iospec != 'b' or not is_array(v.tinfo):
            continue
        if not (_is_scalar_array(v) and _dim_product(v) == 1):
            continue
        il = v.input_label
        ol = v.output_label
        idx = ol + 1
        _w(fp, f"plhs({idx}) = mxCreateDoubleMatrix(1_c_size_t, 1_c_size_t, 0)", 4)
        _w(fp, f"call c_f_pointer(mxGetPr(plhs({idx})), out{ol}_dbl_, [1])", 4)
        _w(fp, f"out{ol}_dbl_(1) = dble(in{il}_)", 4)

    # Output-only scalars
    for v in (f.ret or []) + f.args:
        if v.iospec != 'o':
            continue
        if v.tinfo in (VT.scalar, VT.p_scalar):
            ol = v.output_label
            idx = ol + 1
            _w(fp, f"plhs({idx}) = mxCreateDoubleMatrix(1_c_size_t, 1_c_size_t, 0)", 4)
            _w(fp, f"call c_f_pointer(mxGetPr(plhs({idx})), out{ol}_dbl_, [1])", 4)
            _w(fp, f"out{ol}_dbl_(1) = dble(out{ol}_)", 4)

    # Inout non-native arrays: convert back to double and write to output
    for v in f.args:
        if v.iospec != 'b' or not is_array(v.tinfo):
            continue
        if _is_scalar_array(v) and _dim_product(v) == 1:
            continue
        if not _needs_conversion(v.basetype):
            continue
        il = v.input_label
        ol = v.output_label
        idx = ol + 1
        da = v.qual.args if v.qual else []
        if da:
            sz = _alloc_size_expr(da)
        else:
            sz = f"inout{il}_m_ * inout{il}_n_"
        _w(fp, f"call c_f_pointer(mxGetPr(plhs({idx})), out{ol}_dbl_, [{sz}])", 4)
        _w(fp, f"do mwf_i_ = 1, {sz}", 4)
        _w(fp, f"  out{ol}_dbl_(mwf_i_) = dble(in{il}_(mwf_i_))", 6)
        _w(fp, f"end do", 4)

    fp.write("\n")


# ===================================================================
# Per-stub: cleanup allocatables
# ===================================================================

def _print_cleanup(fp, f, i8_mode):
    """Deallocate temporary arrays."""
    has_cleanup = False
    for v in f.args:
        if is_array(v.tinfo) and _needs_conversion(v.basetype):
            if not (_is_scalar_array(v) and _dim_product(v) == 1):
                has_cleanup = True

    if not has_cleanup:
        return

    _wc(fp, "cleanup", 4)
    for v in f.args:
        if not is_array(v.tinfo) or not _needs_conversion(v.basetype):
            continue
        if _is_scalar_array(v) and _dim_product(v) == 1:
            continue
        n = vname(v)
        _w(fp, f"if (allocated({n})) deallocate({n})", 4)

    fp.write("\n")


# ===================================================================
# Print a single stub
# ===================================================================

def _print_stub_comment(fp, f):
    fp.write(f"\n! ---- {f.fname}: {f.line} ----\n")
    desc = print_func(f).rstrip('\n')
    fp.write(f"! {desc}\n")
    if f.same:
        fsame = f.same[0]
        fp.write(f"! Also at {fsame.fname}: {fsame.line}\n")


def _print_stub(fp, ctx, f, i8_mode):
    ids = id_string(ctx, f)
    _print_stub_comment(fp, f)

    fp.write(f"\nsubroutine mwfStub{f.id}(nlhs, plhs, nrhs, prhs)\n")
    _w(fp, "use iso_c_binding")
    _w(fp, "use mwrap_mex")
    _w(fp, "implicit none")
    _w(fp, "integer(c_int), intent(in) :: nlhs, nrhs")
    _w(fp, "type(c_ptr), intent(inout) :: plhs(*)")
    _w(fp, "type(c_ptr), intent(in) :: prhs(*)")
    fp.write("\n")

    _print_declarations(fp, f, i8_mode)
    _print_unpack_dims(fp, f, i8_mode)
    _print_unpack_inputs(fp, f, i8_mode)
    _print_handle_inout(fp, f, i8_mode)
    _print_alloc_outputs(fp, f, i8_mode)
    _print_make_call(fp, f, i8_mode)
    _print_marshal_results(fp, f, i8_mode)
    _print_cleanup(fp, f, i8_mode)

    fp.write("end subroutine mwfStub{}\n".format(f.id))


# ===================================================================
# Print gateway
# ===================================================================

def _print_gateway(fp, funcs, mexfunc, i8_mode):
    fp.write("\n")
    fp.write("! " + "=" * 65 + "\n")
    fp.write("! Gateway: mexFunction\n")
    fp.write("! " + "=" * 65 + "\n")

    fp.write(f'\nsubroutine mexFunction(nlhs, plhs, nrhs, prhs) &\n')
    fp.write(f'    bind(C, name="mexFunction")\n')
    _w(fp, "use iso_c_binding")
    _w(fp, "use mwrap_mex")
    _w(fp, "implicit none")
    _w(fp, "integer(c_int), value :: nlhs, nrhs")
    _w(fp, "type(c_ptr) :: plhs(*)")
    _w(fp, "type(c_ptr) :: prhs(*)")
    _w(fp, "integer(c_int) :: stub_id_")
    fp.write("\n")
    _w(fp, "stub_id_ = int(mxGetScalar(prhs(1)), c_int)")
    fp.write("\n")

    # Build dispatch
    id_to_primary = {}
    for f in funcs:
        id_to_primary[f.id] = f.id
        for fsame in f.same:
            id_to_primary[fsame.id] = f.id

    all_ids = sorted(id_to_primary.keys())

    if not all_ids:
        _w(fp, "call mexErrMsgTxt('No functions registered' // c_null_char)")
    else:
        first = True
        for sid in all_ids:
            pid = id_to_primary[sid]
            if first:
                _w(fp, f"if (stub_id_ == {sid}) then")
                first = False
            else:
                _w(fp, f"else if (stub_id_ == {sid}) then")
            _w(fp, f"  call mwfStub{pid}(nlhs, plhs, nrhs - 1, prhs(2))", 2)
        _w(fp, "else")
        _w(fp, "  call mexErrMsgTxt('Unknown function ID' // c_null_char)")
        _w(fp, "end if")

    fp.write("\nend subroutine mexFunction\n")


# ===================================================================
# Top-level: print_fmex_file
# ===================================================================

def print_fmex_file(fp, ctx, funcs, mexfunc, i8_mode=False):
    """Write all stubs and the gateway."""
    # Validate: all functions must be Fortran in -fmex mode
    for f in funcs:
        if not f.fort:
            sys.stderr.write(
                f"Error ({f.fname}:{f.line}): "
                f"Function '{f.funcv}' is not declared as FORTRAN. "
                f"All functions must use FORTRAN in -fmex mode.\n")
            return

    # Print stubs
    for f in funcs:
        _print_stub(fp, ctx, f, i8_mode)

    # Print gateway
    _print_gateway(fp, funcs, mexfunc, i8_mode)
