! ---------------------------------------------------------------------
! Fortran MEX runtime support for mwrap-generated code.
! Code generated by mwrap 1.4
!
! Copyright (c) 2007-2008 David Bindel
!
! Permission is hereby granted, free of charge, to any person
! obtaining a copy of this software and associated documentation
! files (the "Software"), to deal in the Software without
! restriction, including without limitation the rights to use,
! copy, modify, merge, publish, distribute, sublicense, and/or
! sell copies of the Software, and to permit persons to whom the
! Software is furnished to do so, subject to the following
! conditions:
!
! The above copyright notice and this permission notice shall be
! included in all copies or substantial portions of the Software.
!
! You may distribute a work that contains part or all of the
! source code generated by mwrap under the terms of your choice.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
! EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
! OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
! NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
! HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
! WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
! FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
! OTHER DEALINGS IN THE SOFTWARE.
!
! Fortran MEX backend by Zydrunas Gimbutas (2026),
! with assistance from Claude Code / Claude Opus 4.6 (Anthropic).
!
! Compatibility: MATLAB MEX Fortran API, Octave mkoctfile --mex.
! Requires: iso_c_binding (Fortran 2003+).
! ---------------------------------------------------------------------
!
! Module: mwrap_mex — bind(C) interfaces for MATLAB/Octave MEX API.
!
! All mx*/mex* functions are declared with bind(C) so the Fortran
! compiler uses C calling convention and C name mangling.  This
! eliminates the need for a separate C bridge file.
!
module mwrap_mex
  use iso_c_binding
  implicit none

  interface

    ! --- Scalar extraction ---

    real(c_double) function mxGetScalar(pm) bind(C, name="mxGetScalar")
      import :: c_ptr, c_double
      type(c_ptr), value :: pm
    end function

    ! --- Data pointers ---

    type(c_ptr) function mxGetPr(pm) bind(C, name="mxGetPr")
      import :: c_ptr
      type(c_ptr), value :: pm
    end function

    type(c_ptr) function mxGetPi(pm) bind(C, name="mxGetPi")
      import :: c_ptr
      type(c_ptr), value :: pm
    end function

    ! --- Array dimensions ---

    integer(c_size_t) function mxGetM(pm) bind(C, name="mxGetM")
      import :: c_ptr, c_size_t
      type(c_ptr), value :: pm
    end function

    integer(c_size_t) function mxGetN(pm) bind(C, name="mxGetN")
      import :: c_ptr, c_size_t
      type(c_ptr), value :: pm
    end function

    ! --- Array creation ---

    type(c_ptr) function mxCreateDoubleMatrix(m, n, ComplexFlag) &
        bind(C, name="mxCreateDoubleMatrix")
      import :: c_ptr, c_size_t, c_int
      integer(c_size_t), value :: m, n
      integer(c_int), value :: ComplexFlag
    end function

    ! --- String handling ---

    integer(c_int) function mxGetString(pm, str, strlen) &
        bind(C, name="mxGetString")
      import :: c_ptr, c_int, c_char
      type(c_ptr), value :: pm
      character(c_char), intent(out) :: str(*)
      integer(c_int), value :: strlen
    end function

    type(c_ptr) function mxCreateString(str) &
        bind(C, name="mxCreateString")
      import :: c_ptr, c_char
      character(c_char), intent(in) :: str(*)
    end function

    ! --- Error reporting ---

    subroutine mexErrMsgTxt(msg) bind(C, name="mexErrMsgTxt")
      import :: c_char
      character(c_char), intent(in) :: msg(*)
    end subroutine

  end interface

end module mwrap_mex
