/* Oct-file runtime support for mwrap-generated code.
 * Code generated by mwrap 1.4
 *
 * Copyright (c) 2007-2008 David Bindel
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * You may distribute a work that contains part or all of the source code
 * generated by mwrap under the terms of your choice.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * Oct-file backend by Zydrunas Gimbutas (2026),
 * with assistance from Claude Code / Claude Opus 4.6 (Anthropic).
 *
 * Compatibility: Octave 4.0+.  We use fortran_vec() rather than rwdata()
 * for mutable array access to support Octave versions prior to 10.1.
 */

#include <octave/oct.h>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <cstdint>

/* Extract a pointer from an octave_value string encoding */
static void* mwOctGetP(const octave_value& a, const char* fmt, const char** e)
{
    void* p = NULL;
    if (a.is_double_type() && a.numel() == 1 && a.double_value() == 0)
        return NULL;
    if (a.is_string()) {
        char pbuf[128];
        std::string s = a.string_value();
        strncpy(pbuf, s.c_str(), sizeof(pbuf)-1);
        pbuf[sizeof(pbuf)-1] = '\0';
        sscanf(pbuf, fmt, &p);
    }
    if (p == 0)
        *e = "Invalid pointer";
    return p;
}

/* Encode a pointer as an octave_value (string or zero) */
static octave_value mwOctCreateP(void* p, const char* fmt)
{
    if (p == 0) {
        return octave_value(0.0);
    } else {
        char pbuf[128];
        snprintf(pbuf, sizeof(pbuf), fmt, p);
        return octave_value(std::string(pbuf));
    }
}

/* Extract a C string from an octave_value; caller must delete[] result */
static char* mwOctGetString(const octave_value& a, const char** e)
{
    if (!a.is_string() && a.numel() > 0) {
        *e = "Invalid string argument";
        return NULL;
    }
    std::string s = a.string_value();
    size_t slen = s.size() + 1;
    char* cs = new char[slen];
    memcpy(cs, s.c_str(), slen);
    return cs;
}

/* Create an octave_value from a C string (NULL -> 0.0) */
static octave_value mwOctStrncpy(const char* s)
{
    if (s) {
        return octave_value(std::string(s));
    } else {
        return octave_value(0.0);
    }
}

/* Extract a double scalar with validation */
static double mwOctGetScalar(const octave_value& a, const char** e)
{
    if (!a.is_real_scalar()) {
        *e = "Invalid scalar argument";
        return 0;
    }
    return a.double_value();
}

/* Extract a float scalar with validation */
static float mwOctGetScalar_single(const octave_value& a, const char** e)
{
    if (!a.is_single_type() || a.numel() != 1) {
        *e = "Invalid scalar argument";
        return 0;
    }
    return a.float_value();
}

/* Extract a char scalar with validation */
static double mwOctGetScalar_char(const octave_value& a, const char** e)
{
    if (!a.is_string() || a.numel() != 1) {
        *e = "Invalid char argument";
        return 0;
    }
    std::string s = a.string_value();
    return (double)(char)s[0];
}
